### ISSUE TITLE
写真が多いと起動時に数分レベルで固まる＆絞り込みが出来ない

### ISSUE THREAD

**Issue by Narazaka** [gatosyocora/VRCPhotoAlbum#11]
- 初回起動時設定をしてから数分固まり、UIが出てからも1分弱かたまる
- 2回目以降起動時はUIが出ずに数分固まり、UIが出てからも1分弱かたまる
- 「今週」等で絞り込むと全く写真が出てこなくなる

非同期読み込み等にしてほしい

環境:
- SSD上のC:\Users\****\Pictures\VRChat
- 直近のものを除き日付別フォルダ分け済み 合計19207枚35.4GB
- Windows 10 Pro 2004 / Ryzen7 3700X / 32GBRAM / RTX2060

**Comment by gatosyocora** [comment]
起動時読み込みが遅いことは問題として把握しています
現状も一部非同期処理をおこなっていますが, 今後もその方向で負荷分散させていきます。

現在, 絞り込み機能はvrc_meta_toolで埋め込まれたメタ情報のみを使っておこなっています。
VRChatの写真はスクリーンショットの名前が日時になっているのでその情報も使った日付の絞り込みもできるようにしていきます

**Comment by Narazaka** [comment]
> メタ情報のみ

なるほど把握しました

**Comment by gatosyocora** [comment]
枚数が多いと起動時に固まる現象の原因はあらかた特定できました
* 非同期処理の呼び出し方法
* メタ情報読み込み
前者は解決済み(847d111ea12560a8ec4e95f4ebe42b4d9f0262d4)で後者に取り組んでいます

また、メタ情報が含まれていない写真は写真名から日付の情報を取得し, それを検索で使えるようにしました 47e4ab2fd51a570b1178ac4921819c040b9da2f4

**Comment by gatosyocora** [comment]
v0.4でどちらともおおまかには対応できました

**Comment by Narazaka** [comment]
はやくなってました！
