### ISSUE TITLE
日付変更線指定がほしい

### ISSUE THREAD

**Issue by Narazaka** [gatosyocora/VRCPhotoAlbum#25]
VRChatプレイヤーのそれなりに多い人々はイベント等含めてプレイ時間が0時付近に集中する傾向がある（21時～24時のイベント余韻とか、深夜勢とか）ため、一連の流れが日付変更線で切れてしまうことがある。

このためオプションで日付変更線を0時以外にする機能が欲しい。

下記（自作）ツールでは対応していて便利なので同じような感じで……
https://narazaka.booth.pm/items/1416516

**Comment by gatosyocora** [comment]
d59991a6b7894f42cbeecc116871160176fa9b51 d59991a6b7894f42cbeecc116871160176fa9b51 で対応しました
本機能をv0.4.1に含みました
https://github.com/gatosyocora/VRCPhotoAlbum/releases/tag/v0.4.1
